site_name: GeoTimeLapse

docs_dir: docs

repo_url: https://github.com/Cristian-Blanco/Geo-Time-Lapse
repo_name: Geo-Time-Lapse


theme:
  name: material
  language: en
  logo: img/logo.png
  favicon: img/favicon.ico
  direction: ltr
  palette:
    primary: light green
    accent: amber
  icon:
    repo: fontawesome/brands/github

extra:
  generator: false

authors:
  juan_perez:
    name: Juan Pérez
    description: Desarrollador Backend
    avatar: github.com
    url: github.com
  maria_gomez:
    name: María Gómez
    description: Diseñadora UI/UX
    avatar: github.com

plugins:
  - search:
      lang:
        - en
        - es
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true

        - locale: es
          name: Español
          build: true
          nav_translations:
            Home: Inicio
            Setup: Configuración
            Quick Guide: Guía Rápida
            Licence: Licencia

nav:
  - Home: index.md
  - Setup: setup.md
  - Quick Guide: quick-guide.md
  - Licence: licence.md

copyright: Copyright &copy; 2025 Cristian Blanco, Ana Herrera
