site_name: GeoTimeLapse
docs_dir: docs
repo_url: https://github.com/Cristian-Blanco/Geo-Time-Lapse
repo_name: Geo-Time-Lapse
site_url: https://cristian-blanco.github.io/docs-geotimelapse/

theme:
  name: material
  logo: img/logo.png
  language: en
  favicon: img/favicon.ico
  palette:
    primary: light green
    accent: amber
  icon:
    repo: fontawesome/brands/github

extra:
  generator: false

plugins:
  - search:
      lang:
        - en
        - es
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          link: /
        - locale: es
          name: Español
          build: true
          link: /es/
          nav_translations:
            Home: Inicio
            Installation: Instalación
            Quick Guide: Guía Rápida
            Licence: Licencia

nav:
  - Home: index.md
  - Installation: setup.md
  - Quick Guide: quick-guide.md
  - Licence: licence.md

copyright: Copyright &copy; 2025 Cristian Blanco, Ana Herrera
